server:
  port: 8000
  servlet:    encoding:      charset: UTF-8
      enabled: true

spring:  mvc:    view:      prefix: /WEB-INF/views/
      suffix: .jsp
  security:    user:      name: test
      password: 1234
    oauth2:      client:        registration:
          google:
            client-id: 888346330439-ms06i1t0dd6vm2629t2q7m7rp674cc7r.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile          naver:
            client-id: ltilJvwKYH5PjmmVGaE7
            client-secret: 21zyg4hf9y
            scope:            - email
            - name
            - mobile
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8000/login/oauth2/code/naver
        provider:          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response #회원정보를 json으로 전달할 때 response라는 KEY값으로 데이터를 전달.  datasource:    driver-class-name: org.mariadb.jdbc.Driver
    #url: jdbc:mariadb://localhost:8001/instagram?useUnicode=true&allowMultiQueries=true
    #username: root
    #password: toor
    url: jdbc:mariadb://121.175.150.249:3306/instagram?useUnicode=true&allowMultiQueries=true&serverTimezone=Asia/Seoul
    username: root
    password: Wnsdlf1!
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
mybatis:  mapper-locations:  - /mappers/*.xml
  
file:
  path: C:/fileupload/
  #path: /Users/gimjun-il/git/upload/
  
test:
  filename: test_file.txt