# 무슨 port 번호가 8000번이라는 거지????
# 일단은 8000번으로 쓰고.. 이거 중복이라서 못 쓸거 같기는 한데...
# 나중에 8010?? 이나 그렇게 바꿔야할 듯. 
# 근데 어차피 나중에 yml 파일에 옮길 거니까 그때 해도 되지 않겠나.
server:
  port: 8010
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true 
      force-request: true
      force-response: true
      
  tomcat:
    uri-encoding: UTF-8 
# 인코딩 (UTF-8) 


# 스프링부트는 기본적으로 jsp를 제공하지않기 떄문에 jsp의 view resolver를 설정해줘야한다.
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  security:
    user:
      name: test
      password: 1234
  # HeidiSQL과 연결이 되는 부분이다. 밑의 주소도 HeidiSQL에서 확인할 수 있다.
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:8001/instagram?useUnicode=true 
    username: root
    password: toor
# DB 세팅 
 
# mybatis가 db랑 java를 연결해주는 역할을 한다. 연결할 애들을 mapper 아래에 두고, 그 중에서 xml 파일을 검색한다. 
mybatis:
  mapper-locations:
  - /mapper/*.xml
    
    
    
 
      
      
  

